### ISSUE TITLE
Respond to init state from SSR

### ISSUE THREAD

**Issue by tomatau** [xuoe/redux-observers#1]
In a situation where the server side render has provided some initial state to the store, the observer won't fire -- it exits early because of the `current == undefined` check. I see this is desired behaviour from your tests.

Could this check be removed? So that the observe will fire for the initial state?

I understand that this could be a problem, as then every observer may need to check for `prev != null` or something.

Maybe there is another addition to this API that could handle data on `@@INIT` action

Or maybe this check can be moved into the `equals` fn? That way a consumer can at least opt in to observe `@@INIT` for any specific observer.

**Comment by xuoe** [comment]
Hmm, yeah, it ignores the initial state in the sense that it will never be accessible via `current`, but only via `previous`, and that's only after the observer has been triggered once. I can see how this is an issue.

To my mind, your suggestion to use `equals` for this would be the better choice. I'll push the necessary changes later today, which will result in a major version bump.

Also related: I remember thinking that consumers may be more interested in the `current` value than the `previous` one, and that the `dispatcher` signature could be better written as `dispatcher(dispatch, current, previous)`, with `current` and `previous` swapped. That way, some observers (dispatchers, actually) may elide `previous` and simply rely on `current` being set. When I published the package, I decided not to implement this due to the check you mentioned, but with the check removed, it might make sense to include this as well. What are your thoughts on this?

Thanks for looking out!

**Comment by tomatau** [comment]
Sounds like a good idea on both sides :+1: 

I'm curious what your main use cases are for this library? I like that this is a very lightweight solution for side effects that can compose well and keep additional action requests out of reducers in a new dedicated layer within an app.

However, solutions like redux-saga seem potentially cleaner to treat the action as a source of truth rather than firing actions in response to state changes.

Do you have some good example use cases that explain how this approach can offer improvements on other approaches?

**Comment by xuoe** [comment]
My initial use case for it was refreshing tokens, which could be defined as:

``` javascript
// src/observers/tokenRefresher.js
export default function tokenRefresher(interval = DEFAULT_INTERVAL) {
  let id

  return observer(
    state => state.session,
    (dispatch, prev, curr) => {
      if (!prev.loggedIn && curr.loggedIn) {
        id = setInterval(refresh(dispatch, curr), interval)
      } else if (!curr.loggedIn) {
        clearInterval(id)
      }
    }
  )
}

import sessionActions from '../actions/session'

function refresh(dispatch, session) {
  return () => {
    const isAboutToExpire = // determine whether the session would expire after a given duration
    if (isAboutToExpire) {
      dispatch(sessionActions.refresh())
    }
  }
}
```

The issue with this is that you can't really use it on the server side, because you can't wait for `dispatch(sessionActions.refresh())` to finish, even though it would probably return a `Promise` whose value could be waited upon in other contexts. However, it would work fine on the client side, since the dispatch of the `sessionActions.refresh` action would alter the state (it could also dispatch additional actions based on the refresh outcome) and components dependent on that state would render accordingly. Given that, an `isBrowser` function could be used within a `dispatcher` before dispatching.

(Admittedly, the example above is pretty silly; tokens could be refreshed once they actually expire, by chaining requests after the Promise of a refreshed token fulfills (it being chained after an `Unauthorized` response), thus avoiding the usage of timers or observers altogether.)

Given the first paragraph above, I'm pretty certain that this package doesn't provide much value in terms of SSR. However, I do think it comes in handy on the client side in scenarios where some state slices must be modified when some other state slice (or a computed value thereof) changes; with the caveat that there isn't much control over the flow of data, other than that provided by a `dispatcher`.

---

I wouldn't compare this package with redux-saga, which offers a lot more. I wrote it as an alternative to [redux-observer](https://github.com/jimf/redux-observer) and [redux-store-observer](https://github.com/jonnyreeves/redux-store-observer), neither of which provide a way to dispatch actions after a state change.

Personally, I have stepped away from Redux and haven't had the chance to _really_ use this package, but I have to ask: what was the use case that prompted this issue? Why was an observer expected to run before the reducers ran?

**Comment by xuoe** [comment]
Anyway, I finally had the change to implement what you were looking for initially. I'm not sure whether you're still using this (or plan to), but in case you are, let me know if `v2.0` meets your requirements.
