### ISSUE TITLE
immutablejs support?

### ISSUE THREAD

**Issue by amcdnl** [xuoe/redux-observers#2]
how well would this library work with immutablejs?

**Comment by xuoe** [comment]
I haven't used it together with Immutable.js, but it will work fine with a custom implementation of `equals` specifically tailored for this use case. Note that you'd have to provide the custom `equals` implementation to each observer (whose signature is `(mapper, dispatcher, equals)`), otherwise the default `equals` implementation would be used.

**Comment by xuoe** [comment]
Regarding the note above (although not strictly related to your query): it's no longer necessary to do that since `v2.0`.
